### ISSUE TITLE
Some suggestion to reduce memory allocation for better performance

### ISSUE THREAD

**Issue by kz-sher** [ip2location/ip2proxy-go#3]
Background:

- Recently, my company project is adopting ip2location vendor as the main IP DB source and we found that this package is running unexpectedly slow.

Findings:

- A lot of memory allocation (Although there are some optimisation changes added to the latest version v3.4.1).
- Map is abused as getter result even though fields are known.

Optimisation:

- Replace big.Int with "lukechampine.com/uint128" (Credit: @calvinxiao)
- Replace map with struct in its GetAll method like "https://github.com/ip2location/ip2location-go"
- Use no-copy bytes to string conversion suggested here: "https://github.com/golang/go/issues/25484"

Benchmark:

- Using Google Bot's IP:"66.249.66.1" as input:

```
goos: darwin
goarch: amd64
pkg: draft.65
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Benchmark2WithMemoryReader_PX11
Benchmark2WithMemoryReader_PX11-12        	  241352	      4778 ns/op	    7014 B/op	      80 allocs/op
Benchmark2WithMemoryReader_PX11_New
Benchmark2WithMemoryReader_PX11_New-12    	  804042	      1355 ns/op	    3928 B/op	      24 allocs/op
PASS
```

May I know if you guys are fine to accept my PR to know more? (incl. "https://github.com/ip2location/ip2location-go")

**Comment by ip2location-com** [comment]
Yes, please send us the PR so we can review your optimisations.

**Comment by kz-sher** [comment]
Hi @ip2location I have sent my PRs for review. May I know if everything is on track? Feel free to let me know if you have any concern.

**Comment by pg9182** [comment]
If you're looking for a faster and more idiomatic library, see [`github.com/pg9182/ip2x`](https://github.com/pg9182/ip2x) (https://github.com/ip2location/ip2location-go/issues/20). It supports both ip2location and ip2proxy, is fully tested, and has been stable and used in production for ~3 months.
